name: Linting and tests
on: [push]
jobs: 
  check-code-style:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: '3.6'
      - run: python -m pip install -e .
      - run: black --check --diff sydent/ tests/ matrix_is_test/ setup.py
      - run: flake8 sydent/ tests/ matrix_is_test/ setup.py

  run-unit-tests-python3-6:
    needs: [check-code-style]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
         python-version: '3.6'
      - run: python -m pip install -e .
      - run: trial tests

  run-matrix-is-tests-python3-6:
    needs: [check-code-style]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: python -m pip install -e .
      - run: pip install git+https://github.com/matrix-org/matrix-is-tester.git
      - run: trial matrix_is_tester

  run-unit-tests-python3-9:
    needs: [check-code-style]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
         python-version: '3.9'
      - run: python -m pip install -e .
      - run: trial tests

  run-matrix-is-tests-python3-9:
    needs: [check-code-style]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: python -m pip install -e .
      - run: pip install git+https://github.com/matrix-org/matrix-is-tester.git
      - run: trial matrix_is_tester